---
- name: Create and Replace .ini files on Windows Server
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Ensure C:\temp directory exists
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Create file1.ini with static content
      ansible.windows.win_copy:
        dest: C:\temp\file1.ini
        content: |
          [database]
          host = localhost
          port = 3306
          user = admin
          password = secret

    - name: Replace content of file1.ini with new content
      ansible.windows.win_copy:
        dest: C:\temp\file1.ini
        content: |
          [Anujsinghchauhan]
          host = anuj.singh.chauhan
          port = 1234
          user = AnujSingh
          password = welcome@123

